"""
finetune_cnn.py — Fine-tune EfficientNet-B0 on candlestick chart images.

Uses the existing chart PNGs (generated by chart_generator.py) and UP/DOWN
labels derived from the 5-day forward return stored in the market features.

The fine-tuned model is saved to models/cnn_finetuned.pth.
After fine-tuning, re-run src.features.cv_features --finetuned to rebuild
the CV feature matrix using the fine-tuned backbone instead of frozen weights.

Usage:
    python scripts/finetune_cnn.py
    python scripts/finetune_cnn.py --epochs 10 --lr 3e-4 --tickers AAPL MSFT NVDA

Architecture:
    EfficientNet-B0   (ImageNet weights)
    └── classifier: Identity  replaced with
    └── binary head: Linear(1280, 2) + dropout(0.3)

Training strategy (gradual unfreezing):
    Epoch 1-3:  Only the head is trained (backbone frozen)
    Epoch 4+:   Top-2 EfficientNet blocks + head unfrozen (smaller LR)

This avoids catastrophic forgetting while allowing the backbone to adapt
to the domain shift from natural images to financial charts.
"""

from __future__ import annotations

import argparse
import logging
import random
from pathlib import Path

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from PIL import Image
from sklearn.metrics import f1_score, accuracy_score, classification_report
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset, DataLoader
from torchvision import models, transforms

# ── Project imports ──────────────────────────────────────────────────────────
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.config import (
    FEATURES_MARKET_PATH,
    MODELS_DIR,
    RAW_CHARTS_DIR,
    TICKERS_ALL,
    TRAIN_END,
)

logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)

# ── Constants ─────────────────────────────────────────────────────────────────
FINETUNED_MODEL_PATH = MODELS_DIR / "cnn_finetuned.pth"
LABEL_MAP = {"UP": 1, "DOWN": 0}
_IMAGENET_MEAN = [0.485, 0.456, 0.406]
_IMAGENET_STD  = [0.229, 0.224, 0.225]

_TRAIN_TRANSFORM = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.3),          # mild augmentation
    transforms.ColorJitter(brightness=0.1, contrast=0.1),
    transforms.ToTensor(),
    transforms.Normalize(mean=_IMAGENET_MEAN, std=_IMAGENET_STD),
])

_VAL_TRANSFORM = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=_IMAGENET_MEAN, std=_IMAGENET_STD),
])


# ── Dataset ───────────────────────────────────────────────────────────────────

class ChartDataset(Dataset):
    """Dataset of candlestick chart PNGs with UP/DOWN labels.

    Args:
        items: List of (path, label_int) tuples.
        transform: torchvision transform to apply.
    """

    def __init__(self, items: list[tuple[Path, int]], transform=None):
        self.items = items
        self.transform = transform or _VAL_TRANSFORM

    def __len__(self) -> int:
        return len(self.items)

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, int]:
        path, label = self.items[idx]
        img = Image.open(path).convert("RGB")
        return self.transform(img), label


# ── Model ─────────────────────────────────────────────────────────────────────

def build_model(device: str) -> nn.Module:
    """Build EfficientNet-B0 with a binary classification head.

    Initially, only the head is unfrozen (backbone fully frozen).

    Returns:
        Model on the specified device.
    """
    backbone = models.efficientnet_b0(weights=models.EfficientNet_B0_Weights.IMAGENET1K_V1)
    # Freeze entire backbone
    for p in backbone.parameters():
        p.requires_grad = False

    # Replace classifier with binary head
    in_features = backbone.classifier[1].in_features
    backbone.classifier = nn.Sequential(
        nn.Dropout(p=0.3, inplace=True),
        nn.Linear(in_features, 2),
    )
    return backbone.to(device)


def unfreeze_top_blocks(model: nn.Module, n_blocks: int = 2) -> None:
    """Unfreeze the top N blocks of EfficientNet features for fine-tuning.

    Args:
        model: EfficientNet-B0 model.
        n_blocks: Number of feature blocks to unfreeze from the top.
    """
    features = list(model.features.children())
    for block in features[-n_blocks:]:
        for p in block.parameters():
            p.requires_grad = True
    logger.info("Unfrozen top %d EfficientNet blocks for fine-tuning.", n_blocks)


# ── Data loading ──────────────────────────────────────────────────────────────

def build_dataset(
    tickers: list[str],
    charts_dir: Path = RAW_CHARTS_DIR,
    market_path: Path = FEATURES_MARKET_PATH,
    train_cutoff: str = str(TRAIN_END),
) -> list[tuple[Path, int]]:
    """Build (image_path, label) pairs from chart PNGs + market feature labels.

    Only uses data up to train_cutoff to avoid leaking test labels.

    Args:
        tickers: List of ticker symbols.
        charts_dir: Root directory of chart PNGs.
        market_path: Path to market features Parquet.
        train_cutoff: ISO date string; only use dates ≤ this.

    Returns:
        List of (Path, int) tuples.
    """
    logger.info("Loading market features for label extraction ...")
    market = pd.read_parquet(market_path)
    market.index = pd.to_datetime(market.index)
    market = market[market.index <= train_cutoff]
    market = market[market["target"].notna()]

    items: list[tuple[Path, int]] = []
    missing_tickers = 0

    for ticker in tickers:
        t_mkt = market[market["ticker"] == ticker]
        if t_mkt.empty:
            continue

        label_map_series = t_mkt["target"].map(LABEL_MAP)
        ticker_dir = charts_dir / ticker
        if not ticker_dir.exists():
            missing_tickers += 1
            continue

        chart_files = list(ticker_dir.glob("*.png"))
        date_to_file: dict[pd.Timestamp, Path] = {}
        for f in chart_files:
            try:
                date_to_file[pd.Timestamp(f.stem)] = f
            except Exception:
                pass

        for date, label_int in label_map_series.items():
            if pd.isna(label_int):
                continue
            date_ts = pd.Timestamp(date)
            if date_ts in date_to_file:
                items.append((date_to_file[date_ts], int(label_int)))

    logger.info(
        "Dataset: %d samples from %d tickers (%d tickers had no charts)",
        len(items), len(tickers) - missing_tickers, missing_tickers,
    )
    return items


# ── Training loop ─────────────────────────────────────────────────────────────

def train_epoch(
    model: nn.Module,
    loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    criterion: nn.Module,
    device: str,
) -> float:
    """Run one training epoch. Returns mean loss."""
    model.train()
    total_loss = 0.0
    for imgs, labels in loader:
        imgs, labels = imgs.to(device), labels.to(device)
        optimizer.zero_grad()
        logits = model(imgs)
        loss = criterion(logits, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    return total_loss / len(loader)


@torch.no_grad()
def evaluate(
    model: nn.Module,
    loader: DataLoader,
    device: str,
) -> dict:
    """Evaluate model on a DataLoader. Returns metrics dict."""
    model.eval()
    all_preds, all_labels = [], []
    for imgs, labels in loader:
        imgs = imgs.to(device)
        logits = model(imgs)
        preds = logits.argmax(dim=1).cpu().numpy()
        all_preds.extend(preds)
        all_labels.extend(labels.numpy())

    acc = accuracy_score(all_labels, all_preds)
    f1  = f1_score(all_labels, all_preds, average="macro", zero_division=0)
    report = classification_report(
        all_labels, all_preds,
        target_names=["DOWN", "UP"], zero_division=0,
    )
    return {"accuracy": acc, "f1_macro": f1, "report": report}


# ── Main ──────────────────────────────────────────────────────────────────────

def main(
    tickers: list[str] = TICKERS_ALL,
    epochs: int = 10,
    batch_size: int = 32,
    lr_head: float = 1e-3,
    lr_backbone: float = 3e-5,
    unfreeze_epoch: int = 3,
    n_unfreeze_blocks: int = 2,
    val_split: float = 0.15,
    seed: int = 42,
) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    logger.info("Device: %s", device)

    # ── Build dataset ────────────────────────────────────────────────────────
    all_items = build_dataset(tickers)
    if len(all_items) < 50:
        logger.error(
            "Only %d samples found. Run chart_generator first (step=2).", len(all_items)
        )
        return

    random.shuffle(all_items)
    train_items, val_items = train_test_split(
        all_items, test_size=val_split, random_state=seed,
        stratify=[label for _, label in all_items],
    )
    logger.info("Train: %d  |  Val: %d", len(train_items), len(val_items))

    train_ds = ChartDataset(train_items, transform=_TRAIN_TRANSFORM)
    val_ds   = ChartDataset(val_items, transform=_VAL_TRANSFORM)

    # Class weights for imbalanced labels
    n_down = sum(1 for _, l in train_items if l == 0)
    n_up   = sum(1 for _, l in train_items if l == 1)
    total  = n_down + n_up
    weight = torch.tensor(
        [total / (2 * n_down), total / (2 * n_up)], dtype=torch.float32
    ).to(device)
    logger.info("Class weights: DOWN=%.3f, UP=%.3f", weight[0].item(), weight[1].item())

    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True,
                              num_workers=0, pin_memory=(device == "cuda"))
    val_loader   = DataLoader(val_ds, batch_size=batch_size, shuffle=False,
                              num_workers=0, pin_memory=(device == "cuda"))

    # ── Model ────────────────────────────────────────────────────────────────
    model = build_model(device)
    criterion = nn.CrossEntropyLoss(weight=weight)

    # Phase 1: head-only optimizer
    optimizer = torch.optim.Adam(
        filter(lambda p: p.requires_grad, model.parameters()), lr=lr_head
    )
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    best_f1     = 0.0
    best_state  = None

    for epoch in range(1, epochs + 1):
        # Gradual unfreezing: unfreeze top blocks at unfreeze_epoch
        if epoch == unfreeze_epoch + 1:
            unfreeze_top_blocks(model, n_blocks=n_unfreeze_blocks)
            # Switch to lower LR with all unfrozen params
            optimizer = torch.optim.Adam([
                {"params": model.classifier.parameters(), "lr": lr_head},
                {"params": filter(lambda p: p.requires_grad and p not in
                                  set(model.classifier.parameters()),
                                  model.parameters()),
                 "lr": lr_backbone},
            ])
            scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
                optimizer, T_max=epochs - unfreeze_epoch
            )

        loss = train_epoch(model, train_loader, optimizer, criterion, device)
        metrics = evaluate(model, val_loader, device)
        scheduler.step()

        logger.info(
            "Epoch %d/%d | loss=%.4f | val_acc=%.4f | val_f1=%.4f",
            epoch, epochs, loss, metrics["accuracy"], metrics["f1_macro"],
        )

        if metrics["f1_macro"] > best_f1:
            best_f1    = metrics["f1_macro"]
            best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
            logger.info("  ✓ New best F1: %.4f — model checkpoint saved", best_f1)

    # ── Save ─────────────────────────────────────────────────────────────────
    if best_state is not None:
        MODELS_DIR.mkdir(parents=True, exist_ok=True)
        torch.save(
            {
                "model_state_dict": best_state,
                "architecture": "efficientnet_b0",
                "num_classes": 2,
                "label_map": LABEL_MAP,
                "val_f1_macro": best_f1,
                "epochs_trained": epochs,
                "n_train_samples": len(train_items),
            },
            FINETUNED_MODEL_PATH,
        )
        logger.info("Fine-tuned model saved to %s (val F1: %.4f)", FINETUNED_MODEL_PATH, best_f1)
        logger.info("Final classification report:\n%s", metrics["report"])
        logger.info(
            "\nNext step: rebuild CV features with fine-tuned backbone:\n"
            "  python -m src.features.cv_features --finetuned"
        )
    else:
        logger.error("Training produced no improvements over random — check your data.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Fine-tune EfficientNet-B0 on chart images")
    parser.add_argument("--epochs",    type=int,   default=10, help="Total training epochs")
    parser.add_argument("--batch",     type=int,   default=32, help="Batch size")
    parser.add_argument("--lr",        type=float, default=1e-3, help="Head learning rate")
    parser.add_argument("--lr-bb",     type=float, default=3e-5, help="Backbone learning rate (after unfreezing)")
    parser.add_argument("--unfreeze-epoch", type=int, default=3, help="Epoch at which backbone blocks are unfrozen")
    parser.add_argument("--n-blocks",  type=int,   default=2, help="Number of backbone blocks to unfreeze")
    parser.add_argument("--tickers",   nargs="+",  default=None, help="Subset of tickers (default: all)")
    args = parser.parse_args()

    tickers = args.tickers or TICKERS_ALL
    main(
        tickers=tickers,
        epochs=args.epochs,
        batch_size=args.batch,
        lr_head=args.lr,
        lr_backbone=args.lr_bb,
        unfreeze_epoch=args.unfreeze_epoch,
        n_unfreeze_blocks=args.n_blocks,
    )
